import Image from "next/image";
import { Discord } from "./_components/icons";
import { data } from "./_lib/data";
import "./globals.css";
import { NavLink } from "./nav-link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen text-gray-100">
          <div className="hidden space-y-2 overflow-y-scroll bg-gray-900 p-3 md:block">
            <NavLink href="/">
              <Discord className="h-5 w-7" />
            </NavLink>

            <hr className="mx-2 rounded border-t-2 border-t-white/[.06]" />

            {data.map((server) => (
              <NavLink
                href={`/servers/${server.id}/channels/${server.categories[0].channels[0].id}`}
                serverId={server.id}
                key={server.id}
              >
                <Image
                  width={48}
                  height={48}
                  src={`/servers/${server.img}`}
                  alt=""
                />
              </NavLink>
            ))}
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
